# Generated by Django 3.0 on 2020-08-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200812_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('địa_chỉ', models.CharField(max_length=255)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='start',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='stop',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_car_name', to='system.Car')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_email', to='system.Customer')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='system.Customer')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_start', to='system.Order')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_stop', to='system.Order')),
            ],
        ),
    ]
