# Generated by Django 3.0 on 2020-08-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200814_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stop',
            new_name='pick_up',
        ),
        migrations.RemoveField(
            model_name='history',
            name='start',
        ),
        migrations.RemoveField(
            model_name='history',
            name='stop',
        ),
        migrations.AddField(
            model_name='history',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_destination', to='system.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='pick_up',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_pick_up', to='system.Order'),
            preserve_default=False,
        ),
    ]
