# Generated by Django 3.0 on 2020-08-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200814_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_name',
            new_name='tên_xe',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='car_name',
            new_name='tên_xe',
        ),
        migrations.RemoveField(
            model_name='history',
            name='car_name',
        ),
        migrations.AddField(
            model_name='history',
            name='tên_xe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_tên_xe', to='system.Car'),
            preserve_default=False,
        ),
    ]
