# Generated by Django 3.0 on 2020-08-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200814_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='pick_up',
            new_name='xuất_phát',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='destination',
            new_name='điểm_đến',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='ngày_về',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='to',
            new_name='ngày_đi',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cell_no',
            new_name='số_điện_thoại',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='destination',
            new_name='tên_khách_hàng',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='employee_name',
            new_name='xuất_phát',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pick_up',
            new_name='điểm_đến',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='địa_chỉ',
        ),
    ]
