# Generated by Django 3.0 on 2020-08-15 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200815_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tên_khách_hàng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ten_khach_hang', to='system.User'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
