# Generated by Django 3.0 on 2020-08-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20200815_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tên_khách_hàng',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
