# Generated by Django 3.0 on 2020-08-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tên_khách_hàng',
        ),
    ]
