# Generated by Django 3.0 on 2020-08-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='tên_khách_hàng',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
