# Generated by Django 3.0 on 2020-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20200815_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='số_điện_thoại',
            field=models.IntegerField(default=0),
        ),
    ]
