# Generated by Django 3.0 on 2020-08-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20200815_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tên_xe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='system.Car'),
        ),
    ]
