# Generated by Django 3.0 on 2020-08-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_auto_20200816_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='tên_xe',
        ),
        migrations.AddField(
            model_name='history',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history_order', to='system.Order'),
            preserve_default=False,
        ),
    ]
