# Generated by Django 3.0 on 2020-08-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
