# Generated by Django 3.0 on 2020-08-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_auto_20200817_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
