# Generated by Django 3.0 on 2020-08-18 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0025_remove_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('số_điện_thoại', models.CharField(max_length=15)),
                ('địa_chỉ', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='số_điện_thoại',
        ),
        migrations.RemoveField(
            model_name='order',
            name='địa_chỉ',
        ),
        migrations.AlterField(
            model_name='quote',
            name='tên_xe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_xe', to='system.Car'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AlterField(
            model_name='privatemsg',
            name='tên_người_dùng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='system.Customer'),
        ),
    ]
