# Generated by Django 3.0 on 2020-08-18 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20200818_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tên_khách_hàng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='system.Customer'),
        ),
    ]
