# Generated by Django 3.0 on 2020-08-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_auto_20200818_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='số_điện_thoại',
            field=models.IntegerField(),
        ),
    ]
