# Generated by Django 3.0 on 2020-08-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_auto_20200818_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='system.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tên_khách_hàng',
            field=models.CharField(max_length=255),
        ),
    ]
