# Generated by Django 3.0 on 2020-08-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_auto_20200818_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
