# Generated by Django 3.0 on 2020-08-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemsg',
            name='số_điện_thoại',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
