# Generated by Django 3.0 on 2020-08-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_auto_20200818_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tên_khách_hàng',
        ),
    ]
