# Generated by Django 2.2.13 on 2020-08-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0038_auto_20200821_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
