# Generated by Django 2.2.13 on 2020-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0039_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
