# Generated by Django 2.2.13 on 2020-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0042_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nhu_cầu_khác',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privatemsg',
            name='số_điện_thoại',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='quote',
            name='số_điện_thoại',
            field=models.CharField(max_length=12),
        ),
    ]
