# Generated by Django 2.2.13 on 2020-08-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0044_auto_20200823_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
