# Generated by Django 2.2.13 on 2020-08-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0045_quote_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
