# Generated by Django 2.2.13 on 2020-08-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0046_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='số_điện_thoại',
            field=models.CharField(max_length=12),
        ),
    ]
