# Generated by Django 3.0 on 2020-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0048_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title_xe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='nhu_cầu_khác',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
