# Generated by Django 3.0 on 2020-08-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0049_auto_20200825_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title_xe',
        ),
    ]
