# Generated by Django 3.0 on 2020-08-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0050_remove_order_title_xe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title_xe',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
