# Generated by Django 3.0 on 2020-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0051_order_title_xe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='số_điện_thoại',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
