# Generated by Django 3.0 on 2020-09-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0052_order_số_điện_thoại'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=999999)),
            ],
        ),
    ]
