# Generated by Django 3.0 on 2020-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0055_auto_20201018_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=2000),
            preserve_default=False,
        ),
    ]
