# Generated by Django 2.2.6 on 2020-10-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0057_auto_20201018_2351'),
        ('system', '0057_blog_text'),
    ]

    operations = [
    ]
