# Generated by Django 3.0 on 2020-08-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUsers',
        ),
    ]
